// Generated by scripts/fetch-media.ts. Do not edit by hand.
// Metro resolves require() statically, so this map lists only files that exist
// on disk — an exercise absent from it renders text only, never an error.
export const MEDIA: Record<string, number> = {
}
